swagger: '2.0'
info:
  version: "1.0.0"
  title: Solartis Rate API for ISO CUP
  description: To get rate for Commercial Umbrella from Solartis Rate 
    API with ISO ERC.
    
    
    Umbrella insurance is extra liability insurance. It is designed to help protect you from major claims and lawsuits and as a result it helps protect your assets and your future. It generally is written over various primary liability policies, such as the business auto policy (BAP), commercial general liability (CGL) policy, watercraft and aircraft liability policies, and employers liability coverage.
host: isocupkbv4-2.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Gets Rate for Commercial Umbrella Policy based on ISO ERC
      operationId: getRates
      produces: 
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "HzhAo4CbF/h3sUqNu9samOpuM/fUjfkVztgESsH7udp80k5yVLm79dKYysDbkulxQ2fJ1UiXAuvNqcbXvy3xtUs/G2H+iTaibVS7MsZQcP0Fq9f9UmDxl6+N+IrrIkNxa9at6iuLrxdsCoBUvuXsthpkZSFvNjltXeTLpaWlyRZE7nDKTBS0KkocOeSUsj8z5zLA8mZnvGmxh4HJbVeqWExdBFyJUz7XJRY9rDW9YV09sOeoJAZddIOJ/Ox3oGX+4u1RH2wEi+vr5YkpgXY1xVRmLdK2SVXrMDedPWZNiqNNjRUUUSq1y4NKyCNxQXjDjiDGofUSvboBuLDE6DT/8oPxVLlKEuu6QNd+Wn2EgxoTfye4Qe71FYzZ6gmgT7Bi09eiWxPkUPcJtrg7KGg23Orp1dqMQWRkgQtjIfQCJapfME56GZbbvXzldsg/xpkz1cUGmko0zdOuDo6rVVSY7l77yj5qBwmKxkV4yJC1b12pie2Yr7xXu7mGPiP19zvahS29HRF5DYYc7sT1GPttRSsZW+9/wrSJiCqoVG0NX9IhHcsN9bAdMn7gzEy4tffqctu1Ix+CpaHNIwia8OelYNDrSVfq7AxSoiQhJjukKOxDcirv00KBIt2SWer42NI5BdfNWDdshrhbme+CEXTh5jdQJUsvnc63erI+Ae0S9noTMBrklNX3N0KrQWc2YZOOyM+LpxwNumqsQuJZjepi8eFgOkfH7dJ2DEcpLAWbSXHAhaP4vBzhGH7ZKia8Zae78bGP72tt3SMc+TgHVbOTcfrzHKz2gGY78EgFmVSzk8yC4A2iI2xyXe7BkX5EfEC2TpbN5pOrbu+gYJWwhutLosJunuvW+cv908fUrBvzOI6ttcS4GqL0su2NawM7pEUBYDvphyZfG99mILy2irt9I4i6LNeyot3EaQ2JG7XdwYx6EyN7cCSruqAMrHdhC4pGXw/27HNlrG8XDi0yv1Lceoi6LNeyot3EaQ2JG7XdwYz2KWF3J+4j5qGwMJQxZQqB5HXuAheyF1X15SFHpFGSUXOHSWYev+OmEAYnkK6tOPtx9gErwTLkhbTD49Ub7omytie2WHF3eq3h0GFuCs3t2g=="
          
        - name: Content-Type
          in: header
          description: Content Type
          required: true
          type: string
          format: string
          default: "application/json"
          
        - name: EventName
          in: header
          description: EventName
          required: true
          type: string
          format: string
          default: "ISOCUPRate"
          
        - name: Rating Request
          in: body
          description: For rating request
          required: true
          schema:
            $ref: '#/definitions/Rating_Request'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Rating_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Rating_Request:
    type: object
    properties:
      EndClientUserUniqueSessionId:
        type: string
        default: "Uniquesession"
      Policy:
        type: object
        required:
          - ISOERCVersion
          - State
          - PercentGeneralLiability
          - UnderlyingHiredAndNonOwnedAutoPremium
          - LiabilityPremiumPremisesTable1
          - LiabilityPremiumPremisesTable2
          - LiabilityPremiumPremisesTable3
          - LiabilityPremiumProductsTableA
          - LiabilityPremiumProductsTableB
          - LiabilityPremiumProductsTableC
        properties:
          ProductNumber:
            type: string
            default: "ISOCUP"
          ProductVerNumber:
            type: string
            default: "ISO_CUP_V1"
          EventName:
            type: string
            default: "ISOCUPRate"
          ISOERCVersion:
            type: string
            default: "RC_CU_AK_06012015_V01"
          EffectiveDate:
            type: string
            default: "2015-06-01"
          ExpirationDate:
            type: string
            default: "2016-06-01"
          InsuredName:
            type: string
            default: "John Smith"
          AddressLine1:
            type: string
            default: ""
          AddressLine2:
            type: string
            default: ""
          City:
            type: string
            default: "Adak"
          County:
            type: string
            default: "Aleutians West Census Area"
          State:
            type: string
            default: "AK"
          ZipCode:
            type: string
            default: "99546"
          PercentGeneralLiability:
            type: string
            default: "25%"
          UnderlyingHiredAndNonOwnedAutoPremium:
            type: string
            default: "75"
          LiabilityPremiumPremisesTable1:
            type: string
            default: "200"
          LiabilityPremiumPremisesTable2:
            type: string
            default: "350"
          LiabilityPremiumPremisesTable3:
            type: string
            default: "320"
          LiabilityPremiumProductsTableA:
            type: string
            default: "100"
          LiabilityPremiumProductsTableB:
            type: string
            default: "310"
          LiabilityPremiumProductsTableC:
            type: string
            default: "400"
          Limit:
            type: string
            default: "5,000,000"
          
      OwnerId:
        type: string
        default: "1"
      ServiceRequestDetail:
        type: object
        properties:
          ResponseType:
            type: string
            enum: ["JSON","XML"]
            default: "JSON"
          OwnerId:
            type: string
            default: "1"
          UserName:
            type: string
            default: "isorateadmin"
          Token:
            type: string
            default: "HzhAo4CbF/h3sUqNu9samOpuM/fUjfkVztgESsH7udp80k5yVLm79dKYysDbkulxQ2fJ1UiXAuvNqcbXvy3xtUs/G2H+iTaibVS7MsZQcP0Fq9f9UmDxl6+N+IrrIkNxa9at6iuLrxdsCoBUvuXsthpkZSFvNjltXeTLpaWlyRZE7nDKTBS0KkocOeSUsj8z5zLA8mZnvGmxh4HJbVeqWExdBFyJUz7XJRY9rDW9YV09sOeoJAZddIOJ/Ox3oGX+4u1RH2wEi+vr5YkpgXY1xVRmLdK2SVXrMDedPWZNiqNNjRUUUSq1y4NKyCNxQXjDjiDGofUSvboBuLDE6DT/8oPxVLlKEuu6QNd+Wn2EgxoTfye4Qe71FYzZ6gmgT7Bi09eiWxPkUPcJtrg7KGg23Orp1dqMQWRkgQtjIfQCJapfME56GZbbvXzldsg/xpkz1cUGmko0zdOuDo6rVVSY7l77yj5qBwmKxkV4yJC1b12pie2Yr7xXu7mGPiP19zvahS29HRF5DYYc7sT1GPttRSsZW+9/wrSJiCqoVG0NX9IhHcsN9bAdMn7gzEy4tffqctu1Ix+CpaHNIwia8OelYNDrSVfq7AxSoiQhJjukKOxDcirv00KBIt2SWer42NI5BdfNWDdshrhbme+CEXTh5jdQJUsvnc63erI+Ae0S9noTMBrklNX3N0KrQWc2YZOOyM+LpxwNumqsQuJZjepi8eFgOkfH7dJ2DEcpLAWbSXHAhaP4vBzhGH7ZKia8Zae78bGP72tt3SMc+TgHVbOTcfrzHKz2gGY78EgFmVSzk8yC4A2iI2xyXe7BkX5EfEC2TpbN5pOrbu+gYJWwhutLosJunuvW+cv908fUrBvzOI6ttcS4GqL0su2NawM7pEUBYDvphyZfG99mILy2irt9I4i6LNeyot3EaQ2JG7XdwYx6EyN7cCSruqAMrHdhC4pGXw/27HNlrG8XDi0yv1Lceoi6LNeyot3EaQ2JG7XdwYz2KWF3J+4j5qGwMJQxZQqB5HXuAheyF1X15SFHpFGSUXOHSWYev+OmEAYnkK6tOPtx9gErwTLkhbTD49Ub7omytie2WHF3eq3h0GFuCs3t2g=="
          BrowserIp:
            type: string
            default: "127.0.0.1"
          ServiceRequestVersion:
            type: string
            default: "1.0"
  

  Rating_Success_Response:
    type: object
    properties:
      messageDetail:
        type: object
      ResponseStatus:
        type: string
      Policy:
        type: object
      
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
