swagger: '2.0'
info:
  version: "1.0.0"
  title: Solartis Rate API for ISO CUP
host: isocupkbv4-2.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Gets Rate for Commercial Umbrella Policy based on ISO ERC
      operationId: getRates
      produces: 
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "cgHkrayYxCQUELzjteEsxZP32zou6UWFXKryWyV7StxpCXrv4Wrw5AgstHJauqCYH0c69BJQL+K19wmFO62JVC00mWQeTs64FO1Exlbj82y1TkII6gSpwRs6d7ZGWuRRKr93tw+FL2s5IOIegd+vfFI1fOHjIs49tuzyDTDyHFd4zLAyXr1iifE21KN5M4KPuj9BeyB02zPGKGO+3S7yojnIPpfpamzEmQMR5XY2iB4UEyLtWCuR9wtM5FtbWHIbzj/bnmLCK6pb8HpH9fDqD3/NUXwW9f8LB/d+oCPp3dUsnCP5Awut2j7mq3nQhacg7xN56OlEJTqV+byM4WsBSYUu+RCiXbic0kx+kBFEW0zB3ahSzo9l23f2dqI051gXd/YRH090RvwO9XpFkmMrxYCoi4MB4x6dvKmhUsgRY80chdGFe6NaXRz5QHH9Ghhtq50njM6Vr2lOJFh8PUPJzbZG2Ecu9vbW5khPB8jeVHKHMwlQswycTzbVogwTTGlvkr0TZgGmgdhmMTzAqe0NTlUoh7CxFto9YYnsQ9eJYRfMUJsg8DOC93m69wudKk1Wu872JSbEKfULE3+hfzAll8W8jF1O8ak3UoBq1qIf/8jytZ9VAQ/L8jhq8mz7Szs5P7yI4K6jdJOzfUWfYeiflteVrPvYVaeXirqCiX8CueLmHmQuan4NsfYl2ws5dZ03SDDvvGZ+/2cwDeXfUTdjaG0IReHMCzI8TUeSoKgniUqIdEWAZvDVT+4dfy964U7httS0iXn/5bYTBwOWgG4YFXXpJj1nd+hMt+DTuJFG2iJS9yCsl+g3HbrW8jjVWuGNw3qMIl92ECSBuAujK6DqEzQVuGnvyP385edvTPMwGAcx2bcKemqTnS/xlog+IUx8vY0RE64FXkwjVhndjLWFxfcXoh04wm/SeWg/Gu0atqYwZ6zz/ELelvOlvddhWJ9OIFN2WcrxuBJox11v2C6GhPwwevhs+xC1WlhKBUkQduC1kqf1U/TEDS2FMmRJIQU2TtWbBVhXDuEEAPDAWxLE3Q0wOgMkgIi0d0ATOk4lp7KmyLzGRjrtZ5GLCp9igKhDrNOt6/r47Q+BN4J2Qie+tjn7JHPeEyme8agVLPvNW0jGl61EwmcoeVHvVHnnGcHnDt1wxx6JWxZE6/FTCLGhTZ9hJ59Z1Hyqzd0bdBKdlTCyeXH+YYd8E6KXdXR2mZLgmvlfjSIeCARWzpU6BJDzdebsJAzzQGaJtopkkyFAwh/nBagajHYhS/1A38t/8pvO+35WgKQCrv9Wq206+AwhGSjM9ANEoNIJb/PMhtIVAgmo5AE5xKz4Du3xEwUCl9IQUwkIAUiLvuyAF9v5+MDZp3JSsw2BRFShIWKyCb39aGjnOczcDJrTX3XHPwhV+l4PK9tE+CLXIBCymsq1xelWZCK2SXWiZzFzq0g9iSJrs1xpL9ES+g4ig5hM7HpujgrCBmUTCvj+VEil3uel+wADNcsz9wHTO/mwRMiD+INLXz1FTK+E5UsjdjQNo3QWL3EkYOEJIvneIjmrr8idyI3WTyELxlMqwIrTb4339qvrpbPc9IsCUhFZCzC7pI/KjiHSnimnmr7qCNPVDKRGR2A6aD/doZZUgmVyi9760e/v1m2/SrUL7DuiQTfxs3UqW6IMURpPXdyZaR8SjBByeLKDHjevMn51EJ8glGgjW9K2k2t1JppHFc920NUvC5cH6vDfj1gnAyTauBeFCleEs1TEe1SO/draOOTvTNK9PYtxC6h/xI/H9+sGq2T8yPI+BGOgffJ72/sZIDhSf3cyftv7t2i3kggt/KprE6bX3iKIrDaYsH+EuX7HtZ5fADGy4cAD6XxEup9YstwtzlGfVQqTCV0pNKbFbIKUi9p0FVwqLhdGJawncRfA2kG9NUG/iQexnYBoQSxctUSGt7BTrAVX7RubDTSkxLODsZ+QD2n9YQIgU3ZZyvG4EmjHXW/YLoaEngq7tOddfEz4y/tURqDA2g=="
          
        - name: Content-Type
          in: header
          description: Content Type
          required: true
          type: string
          format: string
          default: "application/json"
          
        - name: EventName
          in: header
          description: EventName
          required: true
          type: string
          format: string
          default: "ISOCUPRate"
          
        - name: Rating Request
          in: body
          description: For rating request
          required: true
          schema:
            $ref: '#/definitions/Rating_Request'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Rating_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Rating_Request:
    type: object
    properties:
      EndClientUserUniqueSessionId:
        type: string
        default: "Uniquesession"
      Policy:
        type: object
        required:
          - ISOERCVersion
          - State
          - PercentGeneralLiability
          - UnderlyingHiredAndNonOwnedAutoPremium
          - LiabilityPremiumPremisesTable1
          - LiabilityPremiumPremisesTable2
          - LiabilityPremiumPremisesTable3
          - LiabilityPremiumProductsTableA
          - LiabilityPremiumProductsTableB
          - LiabilityPremiumProductsTableC
        properties:
          ProductNumber:
            type: string
            default: "ISOCUP"
          ProductVerNumber:
            type: string
            default: "ISO_CUP_V1"
          EventName:
            type: string
            default: "ISOCUPRate"
          ISOERCVersion:
            type: string
            default: "RC_CU_AK_06012015_V01"
          EffectiveDate:
            type: string
            default: "2015-06-01"
          ExpirationDate:
            type: string
            default: "2016-06-01"
          InsuredName:
            type: string
            default: "John Smith"
          AddressLine1:
            type: string
            default: ""
          AddressLine2:
            type: string
            default: ""
          City:
            type: string
            default: "Adak"
          County:
            type: string
            default: "Aleutians West Census Area"
          State:
            type: string
            default: "AK"
          ZipCode:
            type: string
            default: "99546"
          PercentGeneralLiability:
            type: string
            default: "25%"
          UnderlyingHiredAndNonOwnedAutoPremium:
            type: string
            default: "75"
          LiabilityPremiumPremisesTable1:
            type: string
            default: "200"
          LiabilityPremiumPremisesTable2:
            type: string
            default: "350"
          LiabilityPremiumPremisesTable3:
            type: string
            default: "320"
          LiabilityPremiumProductsTableA:
            type: string
            default: "100"
          LiabilityPremiumProductsTableB:
            type: string
            default: "310"
          LiabilityPremiumProductsTableC:
            type: string
            default: "400"
          Limit:
            type: string
            default: "5,000,000"
          
      OwnerId:
        type: string
        default: "1"
      ServiceRequestDetail:
        type: object
        properties:
          ResponseType:
            type: string
            enum: ["JSON","XML"]
            default: "JSON"
          OwnerId:
            type: string
            default: "1"
          UserName:
            type: string
            default: "isorateadmin"
          Token:
            type: string
            default: "cgHkrayYxCQUELzjteEsxZP32zou6UWFXKryWyV7StxpCXrv4Wrw5AgstHJauqCYH0c69BJQL+K19wmFO62JVC00mWQeTs64FO1Exlbj82y1TkII6gSpwRs6d7ZGWuRRKr93tw+FL2s5IOIegd+vfFI1fOHjIs49tuzyDTDyHFd4zLAyXr1iifE21KN5M4KPuj9BeyB02zPGKGO+3S7yojnIPpfpamzEmQMR5XY2iB4UEyLtWCuR9wtM5FtbWHIbzj/bnmLCK6pb8HpH9fDqD3/NUXwW9f8LB/d+oCPp3dUsnCP5Awut2j7mq3nQhacg7xN56OlEJTqV+byM4WsBSYUu+RCiXbic0kx+kBFEW0zB3ahSzo9l23f2dqI051gXd/YRH090RvwO9XpFkmMrxYCoi4MB4x6dvKmhUsgRY80chdGFe6NaXRz5QHH9Ghhtq50njM6Vr2lOJFh8PUPJzbZG2Ecu9vbW5khPB8jeVHKHMwlQswycTzbVogwTTGlvkr0TZgGmgdhmMTzAqe0NTlUoh7CxFto9YYnsQ9eJYRfMUJsg8DOC93m69wudKk1Wu872JSbEKfULE3+hfzAll8W8jF1O8ak3UoBq1qIf/8jytZ9VAQ/L8jhq8mz7Szs5P7yI4K6jdJOzfUWfYeiflteVrPvYVaeXirqCiX8CueLmHmQuan4NsfYl2ws5dZ03SDDvvGZ+/2cwDeXfUTdjaG0IReHMCzI8TUeSoKgniUqIdEWAZvDVT+4dfy964U7httS0iXn/5bYTBwOWgG4YFXXpJj1nd+hMt+DTuJFG2iJS9yCsl+g3HbrW8jjVWuGNw3qMIl92ECSBuAujK6DqEzQVuGnvyP385edvTPMwGAcx2bcKemqTnS/xlog+IUx8vY0RE64FXkwjVhndjLWFxfcXoh04wm/SeWg/Gu0atqYwZ6zz/ELelvOlvddhWJ9OIFN2WcrxuBJox11v2C6GhPwwevhs+xC1WlhKBUkQduC1kqf1U/TEDS2FMmRJIQU2TtWbBVhXDuEEAPDAWxLE3Q0wOgMkgIi0d0ATOk4lp7KmyLzGRjrtZ5GLCp9igKhDrNOt6/r47Q+BN4J2Qie+tjn7JHPeEyme8agVLPvNW0jGl61EwmcoeVHvVHnnGcHnDt1wxx6JWxZE6/FTCLGhTZ9hJ59Z1Hyqzd0bdBKdlTCyeXH+YYd8E6KXdXR2mZLgmvlfjSIeCARWzpU6BJDzdebsJAzzQGaJtopkkyFAwh/nBagajHYhS/1A38t/8pvO+35WgKQCrv9Wq206+AwhGSjM9ANEoNIJb/PMhtIVAgmo5AE5xKz4Du3xEwUCl9IQUwkIAUiLvuyAF9v5+MDZp3JSsw2BRFShIWKyCb39aGjnOczcDJrTX3XHPwhV+l4PK9tE+CLXIBCymsq1xelWZCK2SXWiZzFzq0g9iSJrs1xpL9ES+g4ig5hM7HpujgrCBmUTCvj+VEil3uel+wADNcsz9wHTO/mwRMiD+INLXz1FTK+E5UsjdjQNo3QWL3EkYOEJIvneIjmrr8idyI3WTyELxlMqwIrTb4339qvrpbPc9IsCUhFZCzC7pI/KjiHSnimnmr7qCNPVDKRGR2A6aD/doZZUgmVyi9760e/v1m2/SrUL7DuiQTfxs3UqW6IMURpPXdyZaR8SjBByeLKDHjevMn51EJ8glGgjW9K2k2t1JppHFc920NUvC5cH6vDfj1gnAyTauBeFCleEs1TEe1SO/draOOTvTNK9PYtxC6h/xI/H9+sGq2T8yPI+BGOgffJ72/sZIDhSf3cyftv7t2i3kggt/KprE6bX3iKIrDaYsH+EuX7HtZ5fADGy4cAD6XxEup9YstwtzlGfVQqTCV0pNKbFbIKUi9p0FVwqLhdGJawncRfA2kG9NUG/iQexnYBoQSxctUSGt7BTrAVX7RubDTSkxLODsZ+QD2n9YQIgU3ZZyvG4EmjHXW/YLoaEngq7tOddfEz4y/tURqDA2g=="
          BrowserIp:
            type: string
            default: "127.0.0.1"
          ServiceRequestVersion:
            type: string
            default: "1.0"
  

  Rating_Success_Response:
    type: object
    properties:
      messageDetail:
        type: object
      ResponseStatus:
        type: string
      Policy:
        type: object
      
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string