swagger: '2.0'
info:
  version: '2.0'
  title: Starr Assist - Non Monetary Endorsement API
  description: |
    This API provides the option of updating changes to the Policy that does not have any impact to Premium. 
  
    Features:
    1. Non Monetary Endorsement at Batch Level
    2. Non Monetary Endorsement at Traveler Level
    
  contact:
    name: Solartis Support
    email: solartis_dtc_support@solartis.com
    
host: starrassistuatkb.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Non Monetary Changes
      operationId: NonMonetaryEndorsement
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "DTC_NonMonetaryEndorsement"
        - name: Non Monetary Endorsement Request
          in: body
          description: Non Monetary Endorsement Request
          required: true
          schema:
            $ref: '#/definitions/NonMonetaryEndorsement_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/NonMonetaryEndorsement_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  NonMonetaryEndorsement_Request:
    type: object
    required:
     - ServiceRequestDetail
     - BatchInformation
    properties:
      EndClientUserUniqueSessionId:
        type: string
      EndClientUserBrowserSessionId:
        type: string
      EndClientUserBrowserInformation:
        type: string
      PaaSClientIPAddress:
        type: string
      ClientUniqueRequestID:
        type: string

      ServiceRequestDetail:
        type: object
        required:
          - OwnerId
          - RegionCode
          - Token
          - ServiceRequestVersion
          - ServiceResponseVersion
          - ResponseType
          - UserName
          - LanguageCode
        properties:
          ServiceRequestVersion:
            type: string
            default: "1.0"
          ServiceResponseVersion:
            type: string
            default: "1.0"
          OwnerId:
            type: string
            default: "15"
          ResponseType:
            type: string
            enum: ["JSON","XML"]
            default: "JSON"
          RegionCode:
            type: string
            default: "US"
          Token:
            type: string
            default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
          UserName:
            type: string
            default: "starragent"
          LanguageCode:
            type: string
            default: "en"
          BrowserIp:
            type: string
      OwnerId:
        type: string
        default: "15"
      EventName:
        type: string
        default: "DTC_NonMonetaryEndorsement"
      BatchInformation:
        type: object
        required:
          - BatchNumber
          - RoleName
        properties:
          BatchNumber:
            type: string
          RoleName:
            type: string
            enum: ["CSR", "Agent"]
          DestinationCountry:
            type: string
          CubaTravelReason:
            type: string
          PolicyInformation:
            type: object
            properties:
              PolicyNumber:
                type: string
              FirstName:
                type: string
              LastName:
                type: string
              Gender:
                type: string
                enum: ["Male", "Female", "Decline to Provide"]
              AddressLine1:
                type: string
              AddressLine2:
                type: string
              City:
                type: string
              State:
                type: string
              Country:
                type: string
              ZipCode:
                type: string
              PhoneNumber:
                type: string
              Email:
                type: string
              EmergencyContactFirstName:
                type: string
              EmergencyContactLastName:
                type: string
              EmergencyContactPhoneNumber:
                type: string
            
      
  NonMonetaryEndorsement_Success_Response:
    type: object
    required:
      - RequestStatus
      - BatchInformation
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      BatchInformation:
        type: object
        properties:
          Policies:
            type: array
            items:
              properties:
                PolicyNumber:
                  type: string
                TravelerPremium:
                  type: string
                TravelerName:
                  type: string
                TravelerDOB:
                  type: string
                PhoneNumber:
                  type: string
                Email:
                  type: string
                DocumentDetail:
                  type: object
                  properties:
                    DocumentType:
                      type: string
                    DocumentName:
                      type: string
                    DocumentURL:
                      type: string
          OwnerId:
            type: string
          EventName:
            type: string
          PolicyEffectiveDate:
            type: string
          PolicyStatus:
            type: string
          StateCode:
            type: string
          BatchNumber:
            type: string
          DepartureDate:
            type: string
          ReturnDate:
            type: string
          RentalStartDate:
            type: string
          RentalEndDate:
            type: string
          PlanName:
            type: string
          PlanCode:
            type: string
            
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
