swagger: '2.0'
info:
  version: '2.0'
  title: Starr Assist - Preview Document API
  description: |
    This API provides the option to view the specimen of Policy PDF.
  
    Features:
    1. Provides preivew document of Poliy PDF
    
  contact:
    name: Solartis Support
    email: solartis_dtc_support@solartis.com


host: starrassistuatkb.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Preview Document is used to view specimen of Policy PDF
      operationId: PreviewDocument
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: >-
            qOgoyA6vZM3Q/DnlQpXl6wQbCcDP5DYFagteTZt/VELMNKQasxqakmheSNcBh3+meJfQHQzrkqUMBShAjRSbI+GqHpNHwnnhGePGI9fBwn7FhRH344xP9ZxqJ7IotHrBOM26rUJ8PmmyOVImRyUGb/vNhv5FzWalI3Ujx/ylCYyU60ff/N7HN2EDoZJiMH12jXG/gq90OAwOQlgUw8PY2tx3HiNi4hDzm3cS5BXL1/ptzr/l4lOjehfCVvyRl7JIIb6n/Aoa5NeAeqsGrXFwhaGuvAOc0m1R845OmZCHgwep5oCFqbu1/ZUGA5e4/Xtz7BoSL81ws23UYQNpFr867LVAXRaTZSCK7NNndFREoaMzio3jOmHpsDudM7/9XkTE8mxcMSo0L0xeqVwvRXHAMFAOGpzzY6syXB1iyxW2CgML/RXTKvn41MY2R9/tSLRDJRkrApdAB9TqDeybuMja5u+/JYxI979mU8SBPF8gT0S28Nkpzs7V8m0Zg70wR2k2RCzRIuheLVABZLz0o4VvbzY/oIJJVoNHjQHNbjJh67aXM4oHUuCdKlcDVXBDsDLtLO/57AmHYkKnvFWo3m9UXxpr8IwmT8v4LYNMcm7neEL/AbbP/t480Qlt6sF8Bg8ze+DuxQ2rC0H082gUcSm5zFu6VZukZOdmJml/ew5VPTu/HqyqW+s+cCQbAnxxJaZcCiGjTynpQjvAN8guaY+4t1u6VZukZOdmJml/ew5VPTvdMR/+Ze4+GyTdGtMhpaRiVxTDTdbSTOCYCezcGVEBlBkT96jMEiEe3nnxlPZ9dQ3d+ghCBVWWIU8hir4HsWi0gNrBiqUBv8Ndd602owpUAd9Bybe6pV4gSA22FVWxYAezThRmldGDJxjmCZ+hBpnsoG7GyI5+dc4XkRNPRxigzddFqX6JT/1uNik+pAoslo4UKKsh4nOAgDtk9Z7f/r4G
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: PreviewDocumentV2
        - name: PreviewDocument
          in: body
          description: Preview Document
          required: true
          schema:
            $ref: '#/definitions/PreviewDocument_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/PreviewDocument_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
            
definitions:
  PreviewDocument_Request:
    type: object
    required:
      - ServiceRequestDetail
      - CustomerInformation
    properties:
      EndClientUserUniqueSessionId:
        type: string
      EndClientUserBrowserSessionId:
        type: string
      EndClientUserBrowserInformation:
        type: string
      PaaSClientIPAddress:
        type: string
      ClientUniqueRequestID:
        type: string
      ServiceRequestDetail:
        type: object
        required:
          - OwnerId
          - RegionCode
          - Token
          - ServiceRequestVersion
          - ServiceResponseVersion
          - ResponseType
        properties:
          ServiceRequestVersion:
            type: string
            default: '1.0'
          ServiceResponseVersion:
            type: string
            default: '1.0'
          OwnerId:
            type: string
            default: '15'
            enum: ["15"]
          ResponseType:
            type: string
            enum:
              - JSON
              - XML
            default: JSON
          RegionCode:
            type: string
            default: US
          Token:
            type: string
            default: >-
              qOgoyA6vZM3Q/DnlQpXl6wQbCcDP5DYFagteTZt/VELMNKQasxqakmheSNcBh3+meJfQHQzrkqUMBShAjRSbI+GqHpNHwnnhGePGI9fBwn7FhRH344xP9ZxqJ7IotHrBOM26rUJ8PmmyOVImRyUGb/vNhv5FzWalI3Ujx/ylCYyU60ff/N7HN2EDoZJiMH12jXG/gq90OAwOQlgUw8PY2tx3HiNi4hDzm3cS5BXL1/ptzr/l4lOjehfCVvyRl7JIIb6n/Aoa5NeAeqsGrXFwhaGuvAOc0m1R845OmZCHgwep5oCFqbu1/ZUGA5e4/Xtz7BoSL81ws23UYQNpFr867LVAXRaTZSCK7NNndFREoaMzio3jOmHpsDudM7/9XkTE8mxcMSo0L0xeqVwvRXHAMFAOGpzzY6syXB1iyxW2CgML/RXTKvn41MY2R9/tSLRDJRkrApdAB9TqDeybuMja5u+/JYxI979mU8SBPF8gT0S28Nkpzs7V8m0Zg70wR2k2RCzRIuheLVABZLz0o4VvbzY/oIJJVoNHjQHNbjJh67aXM4oHUuCdKlcDVXBDsDLtLO/57AmHYkKnvFWo3m9UXxpr8IwmT8v4LYNMcm7neEL/AbbP/t480Qlt6sF8Bg8ze+DuxQ2rC0H082gUcSm5zFu6VZukZOdmJml/ew5VPTu/HqyqW+s+cCQbAnxxJaZcCiGjTynpQjvAN8guaY+4t1u6VZukZOdmJml/ew5VPTvdMR/+Ze4+GyTdGtMhpaRiVxTDTdbSTOCYCezcGVEBlBkT96jMEiEe3nnxlPZ9dQ3d+ghCBVWWIU8hir4HsWi0gNrBiqUBv8Ndd602owpUAd9Bybe6pV4gSA22FVWxYAezThRmldGDJxjmCZ+hBpnsoG7GyI5+dc4XkRNPRxigzddFqX6JT/1uNik+pAoslo4UKKsh4nOAgDtk9Z7f/r4G
          UserName:
            type: string
            default: travelagent
          LanguageCode:
            type: string
            default: en
          BrowserIp:
            type: string
      CustomerInformation:
        type: object
        required:
          - OwnerId
          - EventName
          - PlanCode
          - PlanName
          - StateCode
          - StateName
          - PolicyEffectiveDate
        properties:
          OwnerId:
            type: string
            default: '15'
            enum: ["15"]
          EventName:
            type: string
            default: PreviewDocumentV2
            enum: ["PreviewDocumentV2"]
          PlanCode:
            type: string
            enum: ["1", "2", "3", "4", "9", "10", "11"]
          PlanName:
            type: string
            enum:
              - Air Ticket Protector
              - Classic Plus
              - Premier
              - Premier Annual
              - Basic Annual
              - Medical Only Annual
              - Renter's Collision
          StateCode:
            type: string
          StateName:
            type: string
          PolicyEffectiveDate:
            type: string
            
  PreviewDocument_Success_Response:
    type: object
    required:
      - DocumentInfo
    properties:
      DocumentInfo:
        type: array
        items:
          properties:
            DocumentName:
              type: string
            DocumentURL:
              type: string
         
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
