swagger: '2.0'
info:
  version: "1.1.0.4"
  title: STARR Small Business General Liability - Cancel API
  description: Cancel API is used by the customer to cancel the issued policy
  
host: starrsgl.beta.solartis.net
basePath: /DroolsV6/DroolsService
schemes:
  - https
consumes:
  - application/json  
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Cancel rate API for issued SGL policies.
      operationId: Cancelrate
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "VYrZiKMZcl+PvGTCDNQtV6d9u/wLpGCPSTMbS5uSUVBUDtUXzpC9ft67uSFKxCazYeYkk4DbqOLsUmTWOexZjzcrDAY5r69SZQfDxbvCspzKvwmn1spBp4gOyKGDAEeY0ZXKgR1yppy664EgjIcqTCXK3tjvP96AflbzDx5yaTeiDey1btY21VEiCq8vJfYkhQRRgzTdWZyrj+fy4r8J4G56j0P60ECJQ4jrM+isSDtbfNDLoJpzAPuTMUGM1+2dVTfMRCQ7B+3pa0zNmS4DBF4EBZTpuLwSPm2hSW2Artzsb4dPYPXlwKiW0tgWRxI91nDZi6gtvsxfe/vak75T+vTsCrv/fYMG3nDD2py6v6oYZKLdrPv8YmEzaCNskTLRgvZ+mfYIpturZeTgjWCY5/vOnrEDpKGgv4+fOSH0ieQFpe9hyereJAv3An0ADP+6UER3LrtCuNjKgDuFU2ccPm1a6bcDYm/rOYkqp/+SZokDaEsuiuGQbKKRwbigCn0odRpS14HDrg7bY9OTUv3BcRU2aA5GrjMAaftNqQdqxNqWNVApoXfIysQAbvvFHuFgqaz6DRcc0n8SLE2roEFNwaQOjsvkxxYoFJSL8qg5e2JtCyjeESQB4p56g/Mf9zniXi/8a+VrgCOtYF0NGaLJCwwR0XOlq7d+jw8B7i808EhqyiROJwkq4Qp6tZlB1xvTYa6qykcAPdKrlAYqgxV3HlTlkY9iPUH59FMTzwIY0f2mjwzy6DzYzM28FGwn5KZ0gXhy+38yFTmuxCyd+BAe4/8CgE/mr4mEHEzeGebAPc+tx9GZnQbN8Y6rzMAPrvkAn6OB871NRhkOIAVXwqZwaXSB1ytyjUjo4R02wlI0L/Unq/9p4ymg67K4p0r7hvSMhtDpTuPf77osSDmXpSICouuxMMbHZHYrl4J+UL+58v+JhRAJ8C1viQhyUjZfWeO7vJQhY3eGNiZSVqJLMh0EVTZc215vPSCgzsvbQvaOaPZFC1JHF9ngq6cXWlzToIP5a4BxWy0Gqyj6pXXfvGIFeZO/0cw3TQFrWVuhxdhjPe6aS+gW9ROnx8iLUN4h5a2M1IHhhQeQ25n8Z1FTK5165tPPoOjq9qcHEETZjVBebWsHp+s6FJb/5W1Qx6QZwWrzuyA7o9u9TZWuHO/+ECTJfF60e1wYasA/NX5SwlP/kIXhu60ZcSc+vBWhGA+hD7zcyWKDCzI8TDqI6Yc9YCA5qKmFOlUQKR2EBtfPDneD648a1fXJic24/J4QCdfd6tooSTIX6jmZqT+okVH1elnxrClK4tLjAHonDIXM5KwIkq6YKHSp0AJhM//H43BX1CNyQPKwBFTjXKzGaJGQ34IX5fOJDTPqXMfhfIrhVJ8m/b0/3lq8J28g424N7dAHqFeDJthNqH/hyxH4aqtq9JISX9N4y65sHTFxFmMAKJ0B9lpPcYJnjpXYaOmctjO3aThJPyi6b9vCCXAUcipxoTzP/xB1Fif2U3WuYWC5cs2nBbMbOdBmgCluUPO6l5kLQHkzVTuLRc10ocSzv98Hg9s99FkoqVg4rnctLDp+zvVGFtIJXyvlusHgUHwbEBsiYncri9bimwB+2nCkdZsir/RFF1RhYggI4795U/jVLf7MQoF9BtXpQ/AiK5X1p9+kSGtuoIMTluU2v9aYzjImpSww0M8eM408m7wwEIW/LFiaDIq8TYN+fDioThHXdWOKeJMm8wef//jHtrzWNR0LFZ9EK6LI8DWJCzjeXCjcjn3T8sVZcWLjzlV0XzIDL0OUXudfl3ngG7ABq+iYLpZyq5HuU0PQXkyLFO/E0+pcwkcijnWOVIxrn8SM5QNW4lDgEncl+1m9Ha9eUyfgkl9pteXp7nZu4Ouv2QKTD35RuGUF1a+RsgJ63qq5VzkvB5UWKb6nRICJNG2Y3/AJcHRK2hz4lS8QIibUk0lbXKIK9TnyX3FibuxM+16ZUIUUtIcejJs84mifVkwOpr/dguuoqNRmgVxu6jJ5Pyjor9YJjHnW7+4Aa6+jHDBAxte6vgZV1CHobpMks9iyH1sHv7Kwcv4DJLi5MfdzX5RGy+zUpcyxWxlrGRr3MWCNX7BiQF3DCsvzZz5YMnmo9gYOeOSVsewVacaiqJiofHuXp6iZFGmY7R/yVE4D0Juizwcirn4l0ByVBi/3vpKYnedXYMykh+tvA2JGkowIe9//SuAjj80APz5TK9EBgYN/Ot5FyGUI1j/DVRTUqwgMTKn5uzy1hRxebg2u4KEsS1ygtRYk49fe0XfYnBKTg/EsdZakOuYmHnF2ZnXPLX02BlbJ/DfzXX/VVyS/lk52QBSaOWePxg5jbPwiwdBRY/NCxzl5QwxIAHIxYnojNPm8K7co2kgTiflH9zD7iQW1ygkoUlJS9oyrgufy2gStazkIkmz2NO8DPD+YHmGpxNwYoeKOwVDI9txKQcNbKZIIcFamuWEs73DDzJ14mGSr2elTAoXo8lRIsqTBgPlrkC4PH9IkH+7tGFdknF6zyKLLAIaKRmQafbuFe7iLHbRjgbbAKa8zrlrynOTxQqQ+oWWcBYd4n2wv6IECqYsdtGOBtsAprzOuWvKc5PFmnWPLLeqG+5DytXXcLQZ2qa8ZNd0OAYP0+EKk54NP9AmJyPm8El/Fs7tUIOrx158dLWpb7plel3in2s0eP1CT6NxuUrMYPLaHqljTqJjXeSZ/qQD1JevuVh5lwQ+E2bCi8paDTR2WYgLI7wKdAimAhdsWMx6xQpLXtgmoYCgDXkKuvBu6KLdTaSR7yMlVFPHuE1cLNAzS66SlLOJ89w8q8GRkF55kQzX/mPsFpIhHee5aPEaOgQc4C9JIJXHJaxyQ48ckL3sS1MNGhIM3BJt0abvIUhLL93plWN1/nmdkQFWK6LtIF6lFKkc2X1PGLCFgFuXUsA5idTUZy9SbUJogpj2ULdcaeRqTQ9ehSLlgfJah2C2igyomAKcB/ucIpzQB0qbFxhTRapQcBANAueStdZTtoPnlorPnL7DRx6AZMiFyn0dti0PcKvRBwfqMQcLjtuakmByMKMcpebBzFxFgtRR+GW/zcvj5d9oHXaPyIkPP7AU84Mu0nVk1erL39ROVqDDGEOEsn6jsSWWxZTGVkfAjESNqi8qhIcxN/aGIFursWtJ3MQOwJOKfHASC3iHxE/s8Nv6QvA3nzeQMsejTA/J14wdMqbE0zohUcsdi8uuywNcgySGJjOI2BU+P7243OAzopH0YpUiMxezPGtUfO+mBC7NKeZZu8ArdYkbCh/8ucqXsClKsMTe5eKbQrlY84w2XAetlGc4p1VsItib92mNpXu5l3t6WeJWpVD+lydvx3RyUYExYvjuQGKpOssGLpywr/77BA87J0tb5kMisL4f5rpUoZixyEOI6RBawZdvx3RyUYExYvjuQGKpOssHO9xi9tZDXM2jRg4yOB6jat3QadSYYI67ct5gQFdyvQuHj930+YmsiTIuq9ViwD6l7ipkxJJ1HlsD7Diyi1fr8"
        
        - name: Content-Type
          in: header
          description: Content Type
          required: true
          type: string
          default: "application/json"
          
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "CancelIssuance"
          
        - name: EventVersion
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "1.1.0.4"
        
        - name: Cancel_request
          in: body
          description: For cancel_request
          schema:
            $ref: '#/definitions/cancel_request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/Cancellation_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  cancel_request:
    type: object
    properties:
       EndClientUserUniqueSessionId: 
        title: "Client User Unique Session ID"
        type: string
        default: "Uniqusession"
       OwnerId:
        type: string
        default: "30"
       ServiceRequestDetail:
        type: object
        properties:
          ServiceRequestVersion:
           type: string
           default: "1.0"
          ServiceResponseVersion:
           type: string
           default: "1.0"
          OwnerId:
            type: string
            default: "30"
          ResponseType:
           title: "Response Type"
           type: string
           default: "json"
          UserName:
           title: "User Name"
           type: string
           default: "StarrGLagent"
          Token:
           type: string
           default: "VYrZiKMZcl+PvGTCDNQtV6d9u/wLpGCPSTMbS5uSUVBUDtUXzpC9ft67uSFKxCazYeYkk4DbqOLsUmTWOexZjzcrDAY5r69SZQfDxbvCspzKvwmn1spBp4gOyKGDAEeY0ZXKgR1yppy664EgjIcqTCXK3tjvP96AflbzDx5yaTeiDey1btY21VEiCq8vJfYkhQRRgzTdWZyrj+fy4r8J4G56j0P60ECJQ4jrM+isSDtbfNDLoJpzAPuTMUGM1+2dVTfMRCQ7B+3pa0zNmS4DBF4EBZTpuLwSPm2hSW2Artzsb4dPYPXlwKiW0tgWRxI91nDZi6gtvsxfe/vak75T+vTsCrv/fYMG3nDD2py6v6oYZKLdrPv8YmEzaCNskTLRgvZ+mfYIpturZeTgjWCY5/vOnrEDpKGgv4+fOSH0ieQFpe9hyereJAv3An0ADP+6UER3LrtCuNjKgDuFU2ccPm1a6bcDYm/rOYkqp/+SZokDaEsuiuGQbKKRwbigCn0odRpS14HDrg7bY9OTUv3BcRU2aA5GrjMAaftNqQdqxNqWNVApoXfIysQAbvvFHuFgqaz6DRcc0n8SLE2roEFNwaQOjsvkxxYoFJSL8qg5e2JtCyjeESQB4p56g/Mf9zniXi/8a+VrgCOtYF0NGaLJCwwR0XOlq7d+jw8B7i808EhqyiROJwkq4Qp6tZlB1xvTYa6qykcAPdKrlAYqgxV3HlTlkY9iPUH59FMTzwIY0f2mjwzy6DzYzM28FGwn5KZ0gXhy+38yFTmuxCyd+BAe4/8CgE/mr4mEHEzeGebAPc+tx9GZnQbN8Y6rzMAPrvkAn6OB871NRhkOIAVXwqZwaXSB1ytyjUjo4R02wlI0L/Unq/9p4ymg67K4p0r7hvSMhtDpTuPf77osSDmXpSICouuxMMbHZHYrl4J+UL+58v+JhRAJ8C1viQhyUjZfWeO7vJQhY3eGNiZSVqJLMh0EVTZc215vPSCgzsvbQvaOaPZFC1JHF9ngq6cXWlzToIP5a4BxWy0Gqyj6pXXfvGIFeZO/0cw3TQFrWVuhxdhjPe6aS+gW9ROnx8iLUN4h5a2M1IHhhQeQ25n8Z1FTK5165tPPoOjq9qcHEETZjVBebWsHp+s6FJb/5W1Qx6QZwWrzuyA7o9u9TZWuHO/+ECTJfF60e1wYasA/NX5SwlP/kIXhu60ZcSc+vBWhGA+hD7zcyWKDCzI8TDqI6Yc9YCA5qKmFOlUQKR2EBtfPDneD648a1fXJic24/J4QCdfd6tooSTIX6jmZqT+okVH1elnxrClK4tLjAHonDIXM5KwIkq6YKHSp0AJhM//H43BX1CNyQPKwBFTjXKzGaJGQ34IX5fOJDTPqXMfhfIrhVJ8m/b0/3lq8J28g424N7dAHqFeDJthNqH/hyxH4aqtq9JISX9N4y65sHTFxFmMAKJ0B9lpPcYJnjpXYaOmctjO3aThJPyi6b9vCCXAUcipxoTzP/xB1Fif2U3WuYWC5cs2nBbMbOdBmgCluUPO6l5kLQHkzVTuLRc10ocSzv98Hg9s99FkoqVg4rnctLDp+zvVGFtIJXyvlusHgUHwbEBsiYncri9bimwB+2nCkdZsir/RFF1RhYggI4795U/jVLf7MQoF9BtXpQ/AiK5X1p9+kSGtuoIMTluU2v9aYzjImpSww0M8eM408m7wwEIW/LFiaDIq8TYN+fDioThHXdWOKeJMm8wef//jHtrzWNR0LFZ9EK6LI8DWJCzjeXCjcjn3T8sVZcWLjzlV0XzIDL0OUXudfl3ngG7ABq+iYLpZyq5HuU0PQXkyLFO/E0+pcwkcijnWOVIxrn8SM5QNW4lDgEncl+1m9Ha9eUyfgkl9pteXp7nZu4Ouv2QKTD35RuGUF1a+RsgJ63qq5VzkvB5UWKb6nRICJNG2Y3/AJcHRK2hz4lS8QIibUk0lbXKIK9TnyX3FibuxM+16ZUIUUtIcejJs84mifVkwOpr/dguuoqNRmgVxu6jJ5Pyjor9YJjHnW7+4Aa6+jHDBAxte6vgZV1CHobpMks9iyH1sHv7Kwcv4DJLi5MfdzX5RGy+zUpcyxWxlrGRr3MWCNX7BiQF3DCsvzZz5YMnmo9gYOeOSVsewVacaiqJiofHuXp6iZFGmY7R/yVE4D0Juizwcirn4l0ByVBi/3vpKYnedXYMykh+tvA2JGkowIe9//SuAjj80APz5TK9EBgYN/Ot5FyGUI1j/DVRTUqwgMTKn5uzy1hRxebg2u4KEsS1ygtRYk49fe0XfYnBKTg/EsdZakOuYmHnF2ZnXPLX02BlbJ/DfzXX/VVyS/lk52QBSaOWePxg5jbPwiwdBRY/NCxzl5QwxIAHIxYnojNPm8K7co2kgTiflH9zD7iQW1ygkoUlJS9oyrgufy2gStazkIkmz2NO8DPD+YHmGpxNwYoeKOwVDI9txKQcNbKZIIcFamuWEs73DDzJ14mGSr2elTAoXo8lRIsqTBgPlrkC4PH9IkH+7tGFdknF6zyKLLAIaKRmQafbuFe7iLHbRjgbbAKa8zrlrynOTxQqQ+oWWcBYd4n2wv6IECqYsdtGOBtsAprzOuWvKc5PFmnWPLLeqG+5DytXXcLQZ2qa8ZNd0OAYP0+EKk54NP9AmJyPm8El/Fs7tUIOrx158dLWpb7plel3in2s0eP1CT6NxuUrMYPLaHqljTqJjXeSZ/qQD1JevuVh5lwQ+E2bCi8paDTR2WYgLI7wKdAimAhdsWMx6xQpLXtgmoYCgDXkKuvBu6KLdTaSR7yMlVFPHuE1cLNAzS66SlLOJ89w8q8GRkF55kQzX/mPsFpIhHee5aPEaOgQc4C9JIJXHJaxyQ48ckL3sS1MNGhIM3BJt0abvIUhLL93plWN1/nmdkQFWK6LtIF6lFKkc2X1PGLCFgFuXUsA5idTUZy9SbUJogpj2ULdcaeRqTQ9ehSLlgfJah2C2igyomAKcB/ucIpzQB0qbFxhTRapQcBANAueStdZTtoPnlorPnL7DRx6AZMiFyn0dti0PcKvRBwfqMQcLjtuakmByMKMcpebBzFxFgtRR+GW/zcvj5d9oHXaPyIkPP7AU84Mu0nVk1erL39ROVqDDGEOEsn6jsSWWxZTGVkfAjESNqi8qhIcxN/aGIFursWtJ3MQOwJOKfHASC3iHxE/s8Nv6QvA3nzeQMsejTA/J14wdMqbE0zohUcsdi8uuywNcgySGJjOI2BU+P7243OAzopH0YpUiMxezPGtUfO+mBC7NKeZZu8ArdYkbCh/8ucqXsClKsMTe5eKbQrlY84w2XAetlGc4p1VsItib92mNpXu5l3t6WeJWpVD+lydvx3RyUYExYvjuQGKpOssGLpywr/77BA87J0tb5kMisL4f5rpUoZixyEOI6RBawZdvx3RyUYExYvjuQGKpOssHO9xi9tZDXM2jRg4yOB6jat3QadSYYI67ct5gQFdyvQuHj930+YmsiTIuq9ViwD6l7ipkxJJ1HlsD7Diyi1fr8"
          BrowserIp:
            type: string
            default: "127.0.0.1"
          LanguageCode:
            title: "Language Code"
            type: string
            default: "en"    
          RegionCode:
            title: "Region Code"
            type: string
            default: "US"  
       Policy:
         type: object
         properties:
           ProductNumber:
            type: string
            default: "StarrSGLENDR-1"
           ProductVerNumber:
            type: string
            default: "STARR_SGL_2017_V1"
           EventName:
            type: string
            default: "CancelIssuance"
           EventVersion: 
            type: string
            default: "1.1.0.4"
           PolicyNumber:
            type: string
            default: "1000202169"
           CancelEffectiveDate:
            type: string
            default: "2017-07-15"
           CancelReason:
            type: string
            enum: ["Insured's Option - No insurable interest","Insured's Option - Other","Company Option","Cancel - Policy Change","Non-Payment of Premium"]
            default: "Insured's Option - No insurable interest"
           CancelType:
            type: string
            enum: ["Flat", "Prorata","Shortrate"]
            default: "Flat"
           
  Cancellation_Success_Response:
    type: object
    required:
      - RequestStatus
      - Policy
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      Policy:
       type: object
       properties:
        ProductNumber:
         type: string
        ProductVerNumber: 
         type: string
        EventName: 
         type: string
        EventVersion:
         type: string
        PolicyNumber:
         type: string
        CancelType:
         type: string
        CancelEffectiveDate:
         type: string
        CancelReason:
         type: string
        TotalReturnpremium:
         type: string
        DocumentsInfoList:
          type: array
          items:
            properties:
              DocumentType:
                type: string
              DocumentURL:
                type: string
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
        default: "FAILED"
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
        
