swagger: '2.0'
info:
  version: "1.0.0.1"
  title: STARR Business Owners Policy - Reinstate Preview API
  description: The reinstate API is used for  putting back the insurance policy back in action after a lapse.
host: starrbop.alpha.solartis.net
basePath: /DroolsV6/DroolsService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Reinstate API for cancelled BOP policies.
      operationId: ReinstateIssuance
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "fkL92f61e3NOKN1REaZSNlt3tBgSsoeZLTZhCQFAbaacLPw3y4E0ycJ8o03yRjctm9SqODQSR0XUIHnGAafYg820VzIe1aUIk0BnWr9sJg80BZ5Tc6DlPyEKVa2nQ2EQf+Ug72ntpTUqRl4GjinGtkPiSAoCLBrmPs7RuuukLtYDij8gGVPv8pTwSSWR6CdF4oAifo3LL1ZKLvqLWYHKyaI3H+1M+nq9A6aWr+dd1B0+YQS9OUttMT359fhwMtPhLxpem+FHFYN9XrETMZ0RyMR1QEGPjGsvNDyVpG5aOXTl9YXMi2yGfv3ZlyOzY1BQJkUjDe7oUiK+56jpfHUweSRZo6227UB2MhMix6LsJi+sWoe04VD5Bpk5P/b72mAFWgGhJGD8nSbr3lTt6PHb9uk5Dvh08bvMuWI9tckvdwLSowCGKvxvKcHD0M4X6rEePeBPgKKWqUGFnFB7H30Tya5dO8n8IpGE09aw88xsjcDGf4M8OjDBmJRDPqhO8dk6mqL5V1Xsfj+BInmmLTsvBxadB4TnMHk49nChWIpagHszHDZgD+W4m3c1UbAMOU9fJFNtFwEsrYj4hj3cua+LKvnsFjArphIL5J2fGmFIYXIx9mNKgwe3llvpD7p/n3cJwojqEMVMZqZt0Z82JfmvJnJ8IKonzJy6HO1BpJ5uvSD1Y4ay3DJigvjmmNFQyqT6nm7ADu8zirnqrqIPp/JilFFMDITHIBw23SHWkmrI8NRxUrjm8OjcmlbOSB3VAK7jJwpCVOTsZp1JgCZBotj/1Ri59HjmxzP+aIe+lfHei24JhaEy3/UxjVQP9BxsY5KPmcKoOosmyZFqirDL7eXP/pP7E+TOnBiGKGWXrG7I6GeSJKP2a7whLlXvo8cns5731FJTYVFYumodckM8HUhlpChtFJtLB0kFfSRZEtYVug6/rqh10MbdWEM0DkKGGEYBbRTiTb8HqhkeXHO5wQHmlYMAEmR3ng8nMPFvfjsxk54daOQw3sLfcmqGewvlaaaySNArgptSGjJ47gzX0Lpv/Rhou7+po613cTzJgN3949vek3c70SxEXJeFDug/VApu1R3D68+AnEOjA7Confgz3yT/Re4ojtn/FfTc0TXafrTMuPLtL8AZ9ARxmwK3POsYUoOGTeyxMtDQgQYfRAJgsyA8quYuD6coT9wj/2DFy6YfFy0KgM72rxuu5F7Gn6HIn2W/cULUZMoNHcI4udQ2is5H8cz7qX8yqZviSTwsVcNq+o1+3kAc8d2dQCxHMNvtZQLxjtx1jvG1Ch3gXLaR9uP9xp0CwyrvYAFLYvST/bu0rUT+kgv9xj+ndmsGFfR56H8jHg/AXEjA+AS+AgVTHF8UGX3mgWtKgUiv1H+QunPvrd1bPFVggweqsn5hGUHYo+wFzN+KP1jQP7zHMUTpZ0OJiFZHuYF+dr6kWhZnjZGCuwsU2zYQGSbon+S5n+nAwOdy0+WVDHUnZUYemm/AuMESwF7MOkbGoy8kWcuRHOyXZyyOtUsh9M+CnG6c9LK6EvSfQswt2wFvGNqSSoNHQIKz7wIUAVjo61qiN4gfzTo6M4xz6CjBXI0k7+jvCSy/AKIFCZ/NR3uj3WFfnzaQMAGSfjuF9lPy5u3jQ1EMEH8no8/ixnWqsD+BPkC0WKH/J0mP8otHR7NWetiHCRo8d5HAGfJgnejMaxDtHlUN21Mpj84fzyS7c9duZnKeyuGKF86UsBfGWoaSdINcFEQwlTLvk3oICc8ciuKQzEbHpDf6DzjXufznScem44cibJ6GhHkPI5iJtrSffid8d4IGw1lIn2rluYE0Soa8BCLquclglUlQW1dgbFqxcvvlSVmErfg0ELDqqXkr6JsyqO6L4Dcd97HTrz+gl6POAhI37C3WbKrbkAr/T62XUCkMI5OsBwJGOcmRWBUMr4p5Q+tNkMNbbMcte9aieGv8UbXIQMePNiHOzNBcVvVq8OOGTnx7K8LIWj8mwC+hYv4fHQ/5Qx5+dx+vFAlyMdEV/1Pr8E2yzEk6/xB915o6f7Aayu34PYNyf8e0HFOsPIXDXT46F8rzvdEOZBLYTP5n5dABsu7+Tw2hSR9O3foVQhWOlD+vPSvuTak05d5jB3Xb/kPvn+HNF7ZNnytI0zcQh2GK4p7VPXjKfOY61ydb74FVQyKcDnm1oDBEQIZFiWsEx67ys7HaxQBl+EM1LmCeYFkjAx2K+krl3WWM30tdF7WGDf82hvmpy1vWbOA+38E4KVafBGFgtA/vajjWm8jizuXil3OFlXALejLIHDCZHWJkobOP7Up1Q6phapdCuU/mNbBmDfiFbf57vknDR0caDu1WKNSVuF2shWQf/BBMmtvNTdLQtctKK5W6CKmY1T65jJx5qV9gi/BWb8hDaZCm9TkdPaxEMKlvCoYQWhliEOXOv3vGKCg2FMkOW+pRlLaKkSXtdbI7ICeMGG8AVHyVZd1p997L1TwqIJImpIE1tOHV764VKJ3GQRJLpX4JZhXzd0JjAHtv27+oqzElP+fpHiA9qwersDB6UfCfM8Z6djoHGaHt0G7G9DyyR3BKSziBf0F/MP/GD8IE/aVDwt+RXi+OP1j0KaZfS8c3wsHs9+WwlJ5LU/WqF+KeVCOkiwOIFV3DdQY2xYymsBR3itrmRe96gpPFkXt0MXWGz78JAODf7Goo7L4SlGk/tu/hg8w5Hdjl8ZKWOLQTNC9kyb7lGkZuNHzFVmcIgaHGkY4Hih8mAebzHhDcoWj/AQrTYuGCEc3zQBmod1d5RGpcyTO0qV+/JAhKJwEYqNyFahUmLPycbULmW2apEiu795NACYSZRD0KhwosAb3l6LE28i0VfERpi193G3dx7fejpNouISHuNMnYB5m6pFfGhnyvjnHiRJWfMmgQYOJqd98doqy5826ohShzldb3lSi3Or1jTTiAU0LVZj1KOjDHMamjtSZPKw6hlx2RNm784mWqXXQIQ0g/D4pPFFnBRiBUvkKf4jMO49NL/xw8lpvsdkLOqxUdHg1le6r6Lfd1EAr+cjhLq7Ncqj1b939DYgpm1GU7Zv22/HwHf6N7xXVnrfR2m+OBeof0eEXmFTX2Ap+w3jniDzY8kjQJLJ8nf5MgEo+5kjV3z1ht2CRJa71eXVbWFG1k/6+xG0O6j5W/JOMFJVxynk5BGwZ7iTkjgXEerVdjq1tF39nTXtIPrd3QtBAk/uja/E5DN5k6vbZqcZ9ETr77DefzM8Kxw+/THkKrgjf1Bxflr/bSdIWWzZpswrNBOdI6HPV21b8cmG2kFuT+dQspTX6nt9xmu4Qp5OeYvSkQN05mMJjZmCQceIQkWkoi2thjhYjjBMXvHyXRsdMCLFLJKR+ugcVjzaxmkC+spGDy1odYMy8/ximR7e93+mqt/GkPf3bxPyy9ZrDIeBGTiHVSPW/gtycdWuOiuLZ6WVP6RH5Tjov8v5plp6r1FOoyTw6gJuLKqU/nFyLFd7eI7Z6jrDYWFz//GOl3EHlT0TQ52YnJOL6f"
          
        - name: Content-Type
          in: header
          description: Content Type
          required: true
          type: string
          default: "application/json"
          
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "ReinstatePreview"
        
        - name: Reinstate_Request
          in: body
          description: For Reinstate_Request
          schema:
            $ref: '#/definitions/Reinstate_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/Reinstatement_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Reinstate_Request:
    type: object
    properties:
      EndClientUserUniqueSessionId:
        title: "Client User unique session Id"
        type: string
        default: "7Eadfad4444"
      OwnerId:
        title: "Owner Id"
        type: string
        default: "24"
      ServiceRequestDetail:
        type: object
        properties:
          ServiceRequestVersion:
            title: "Service Request Version"
            type: string
            default: "1.0"
          ServiceResponseVersion:
            title: "Service Response Version"
            type: string
            default: "1.0"
          LanguageCode:
            title: "Language Code"
            type: string
            default: "en"
          UserName:
            title: "User Name"
            type: string
            default: "BOPAgent"
          OwnerId:
            title: "Owner Id"
            type: string
            default: "24"
          RegionCode:
            title: "Region Code"
            type: string
            default: "US"
          Token:
            title: "Token"
            type: string
            default: "kMMV+5coRaP0LAqnFEIIvY+U19gRsGs6p9dSX8+actKAT7iJKK8+M9/djPLSR1R0bxlYA4OE0gGXArO3pFK8YaoUvpDersXEZA6W8Dq1ny42MhuPdxY/AA4dGl3U42kwnjphkcdmmvxsyuEoTlFrhiWph77hDEfyUtYJ4N2phiTQwrs5rtZC8qJLLY+pCth4iOfihk//O8iUOk5pjZoOEd2p6PMJ23HcA7rmUdl1IvgrxcuQymNqWNgcYjir7iOIUeDZI3tRDbgL06qL6Q76DSslbeV859MLI2RO7EQOaKw1QId4jK4B98FSW2JOoIUTP2h38fsZ2WRPvPdwfKFcwEY2g+ah5zOa9zCdXzb5YFW/ChDDTKRULT7ml2GRhYR/dCebbrdRTh2bJ8HcM5CQc1ZqPYdbiUbN0yK+V0MCLUDe+mYuxXGHoUAn6mGzxz7QQ9lP4pL1nEO+/RzjkjBg59BztctwCe+gHdYARSJMjBZPKNmpQJRwegl8dhyQWdmHsoE1LoLAT2xwrT/8Zsl0ctW2liF1ya0HtekKZpMWpZ3yuwK8xuEpVMpsdLuJy3feKQl8CxfI5ip6gIf0aiQdkEv4SYcUaN07zSpOYMEoaFYoGZjELwABpayy2xGbPWB5CEbP+ZE7KhruDn1g3aktPkZQG9/8FXlwIpRWw91wqGR7ngoBQq7jfHt4e7hBfqMNj4qVDBeEP5SaaASEnfilW9eJ6SMZlxWnS8hd8ZfZ/U915AL6fH0Bp/ThGjEm97VjVhMkgMBxUoq9+CTXEOsSg/aXVUhFp1K1nWtVeh3XFoe/U9WA3/qzescvIDQzTgK12RxUzyqWWFiguJWt7m4B9AyulAQIGPlmJVEIwsLRN3Pn6MPfFjVRvkASBjNX0xQUP5orDLSOhTkdd/J7v/AUXKuuXSlODNRoeDVogcqA1FrhS6WUJEbmgnOdmtxOr/lvtQ8riT4J+HmastPGIKUqMEf821fPmXgu9g09CGm079SuVgaKi9XcIU0p/Qnn2m/XaQcrTKuwqG0/gW1DQgabZouyQXmTCpc99QijzLV99vIwgsPNymyC5YhE34Ekb3XyFbJNSYq+vZzsUHabUF1S3/zE42g3ysy1CfGVw9PhxozL1XpCPyJjwRDToKxjJr8xeuEp1jGYlx6HeXdOykCEAS9uOH0mfCCOnj3+cMI9+6goba3Ktep/ohQxdgy2y2tRZKbAVX5rTdJTUKHSbtD6ixjZj2jETyS4m8WWgNo4uZBj46TF3IPYwIGAzJdQ2HiE4mFbsBHtiIjofJzAMRVqVGIX8Q3VD0EbSstPldj/zJNCBrc41jEbTcoCQDSY478m73AaqVBDTWgjplbd0yizYS25ypfGVfczb68juBGSNZHFhU5k9OXHoBirIaSbRFfymWHKdn2YCXjtIHx65+ye86oMA8IYDlJ+01KWwsj/ytV/Gw4ekh33AWM5mtf2qlXyxHR9qrrQTVRTY+KyVSB68zKjCF5rHmju62K4HM6FArthJckHi6Cii8ayDO5h15hk756wr+jUduPYzN5I0mhH/a0Qyx5BH9WElRsAfoPD7nHV1S37vT2C+8R8/Nv2Iwoo1D2SvLSvmfz5jcKEjm+7qKlV1aMYDEuJopP/S4PLDkmHvw2PdU1tTVVYK8dJ7SPZPa8S5OpEP8CcUs4JAN0O6INC7YMcCCur483Ni4D3f5Jcs2m6O+DzshqaiZ8E9g34SEkmK+AE3oI3SyFP999AJ7aty/Uh30xPAqL8maotvXMVvLwg6eEF1Q3DxvvBILICo4lF6hao/aUTOaXZ7lJ0grvsmPMniWHGkm0g61FL9IE275uraHBHuyfvzRsYPEqlDRzJV8N3VLmZQJ5ADfSdndS4QruGymKZ8s3Dia3gf2HTKlPaKSOEAI/+Xq0jUEBTVopd27MU79Y9obs/39pSqpaB3zeFzjndrTHtRGZFiHHFVpYBeGf1QhQc5ziE6CgBwHDb1NAC1oH16YjR3xb0oA=="
          BrowserIp:
            title: "Browser Ip"
            type: string
            default: "127.0.0.1"
          ResponseType:
            title: "Response Type"
            type: string
            default: "JSON"
      Policy:
        type: object
        required:
          - PolicyNumber
          - ReinstatementEffectiveDate
          - ReinstatementReason
        properties:
          ProductNumber:
            title: "Product Number"
            type: string
            default: "StarrBasicBOPENDR-3"
          ProductVerNumber:
            title: "Product Version Number"
            type: string
            default: "STARR_BASIC_2016_V1"
          EventName:
            title: "Event Name"
            type: string
            default: "ReinstatePreview"
          PolicyNumber:
            title: "Policy Number"
            type: string
            default: "1000602174"
          ReinstatementEffectiveDate:
            title: "Reinstatement Effective Date"
            type: string
            default: "2018-02-01"
          ReinstatementReason:
            title: "Reinstatement Reason"
            type: string
            default: "Company Option"
            
  Reinstatement_Success_Response:        
    type: object
    required:
      - RequestStatus
      - Policy
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      Policy:
       type: object
       properties:
        ProductNumber:
         type: string
        ProductVerNumber: 
         type: string
        EventName: 
         type: string
        EventVersion:
         type: string
        PolicyNumber:
         type: string
        ReinstatementEffectiveDate:
         type: string
        ReinstatementReason:
         type: string
        TotalReinstatementpremium:
         type: string
        DocumentsInfoList:
          type: array
          items:
            properties:
              DocumentType:
                type: string
              DocumentURL:
                type: string
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
        default: "FAILED"
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
        
