
swagger: '2.0'
info:
  version: "1.1.0.1"
  title: STARR Business Owners Policy - non - renewal API
  description: Non renewal API is used to generate the non renewal pdf to insured.
  
host: starrbop.rc.solartis.net
basePath: /DroolsV6/DroolsService
schemes:
  - https
consumes:
  - application/json  
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Non renewal API for Business Owners Policy
      operationId: Non-renewal
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "7ZDKd4zRfc/19dgAeEIJOsujdeTBKSZT07k5R+P3XaNaPPkpaCCwn7XDv6PPTQTk4RqehB9pFxBFPB49duOQiZytnoQ2s99yFb0LWZvfX/nAZMPTRLXBY5w02kFCY44U0CgzlLgizTFxRqvGEo3ZEC+1YCqwEk/pt24wSsD/LWio6PNwG1F/TVIlUBXR4lZSCPwTpjSIMEcYfTDqp4bijTG06qWUvjnMMfQfSh4Nftb5TWvmuHuEeLLupZ7AZMGoWQQDUCyr8u9ENXmVRGUMYSf0XOZa2acYMvGQdnAb9VSVlhQy6U1NWb0PZSTIfhaS5vGmRZ3cAFES3SyrK6RJXhPQKgQjrje+l5HTcT62eUOtZniUcpyUELMBXcUG0TFz7pYPrMtKkwxMjGuA7/MKJtm11OMbVyIjMqGMEdux1GRcH3qiK7awPuYE+6eFUeviFO1uXQu8b4dySj7sCP091U+yDH2xqm+JBIb2loz0/D+BLrjYeiW3N5bzspx2zoUwqEiqdTrsYr8tWyBraUUaqsYeBu8rsaVAw5tifloBgPe94NOkjnQ6vgsEChZFNo1AdEAniLPUbhTE2LXyNj/HWjBXxNItP/Mxy4lC0iXUqU6twm9wO3xTJpRTxgsFPp5rte7dA+FsgZuCAqvQrdS0WUOVx8HsQOO0rcTbHI2FK+YRmrYWNusPyXRrQSU+6SlVFcreDVQmiqMFYTu647PhOCLsIhEp7iTBVqYVFY9uk4VV8AvZI6rRtkAQFHe3bGxM1Nucpcbb++RQUrPUdzJsGvpOomj/oLkRKS00h77PWGPXHDemrD8dhxG5b3dYIHYgMf6NnUAsWJ5hmzaV8K2WF9HRddmI0FZui81nFifyDzwcgXZ/o2sshJrV+UjKRgGIgmxhBQXiHvIdXFUt2rpMYU9VAOnQK+Ct1xysPWKWUys798NTy5Nd+A4QNeT479D1tD88mbNKCpQVtMMsAfNBr5ZDnVd3PXUtMrCBFr1hXzvcz5A4SaDB+pHecQQV4KsdAxGW3vcKt7LIzirhCXeShhtxb4Tu+lbSVKJdZzLx5uHGIpzZwR+x+8FB5c/di6+PfW+0vqSIDVYxPE8EGflil1I7HfqFrqs9ExnIJEF1UOWXwGn0s+f74lCossDQpGLVWXmQO5xRg03Fp4sIs3ELPkJK0h09mN9v1QsTQL3InbWlGf5U2xXuF9mnszk/D8UXKTYk/6kWSsp0fl+BVOcj9Q0lLU9xeHlea3mNAAcocgqrwVjRP597Ps8jBTG18PFhiv+D4Zg/NVp236+QZi7/qBuD174AfNRhmLYsiB0V0KEIQY+wHOYMXb5oSCpo0rCmfBlMmlbIFX32UruVPqqr2BpyxY1JCdqGUwuWUK97hrmWY1zSKB/Rd5YEL+RS/j7meiG0RGiSK8TTywVB3s0mgj5eI/3u8bMs1SXwZDyocENybh1gORygpWm5QMflC/pj3q2gLBCFb6yhMJ2cIFUXCenCHlJU4gM+rcSRrlMEuDu6tS10d69M4C7gP5A6x29AV4qTjj0tq/JFWDYBoG7f5vKYiF/Av2LUx5jHeZ4wV0n1WNoN4y6l6qB77kTYuiRRJwWal+/4TbEFRVt7NavLr+4S+lg11X2fRFbh9WTtOg1S7WysoLWqeY00/SbjhV8w2+YNvxkcBMyNjVKoMkMbFZBCA9DN+jd+rBQfCNlIm13OPz/lCjJSDFrj3pItA4fUE4EPIqeNiCG3L7CtDx81gFZrMgZI0TTNrdWLpDypNR+gjrK6z/pcJsoR0poF9XXKIKJOdvR14/vEzn9e3666+QYmR4BIzRA9BEqz5TnrnO33baz75SRQoRsQCUf8GOLszwrNJyBd3HdV9vVop3wvtnbvPi3AC4UqmpA4/Pbn64l1WtfcSYyMilReQ0m1ZsQ0ps5e57zV0hUGcHsGO40GLG4EkvNH+YnheClc4w8a3tws8f3mbrtvCT/EvP7jo4PTLD8mGVS2wEiMD+UPXG5wh6+1MOXNMsudR0b7SKDvbMyexoGsreHqgNeKrb4XsFLRmiTY+88EbipwIkp6oSemymy/UeTanYg3MHQY/iKprou4ppcowwqIRIqszWC1/AVt7CBeN9zSVOMhnKh1TCagiNHkIIwDQTrP8Tv6jXew1tmj8w2Z82KEDb+PKnbQ6eh7vlOZpEDgp/wpZrzG22b1vvHkCG+vUr6cx5keUu9SGz1wI3mzwcLSiSNLwkojLaLqQ+oi74tiX7w6twDFHP48ioS5xsGczWvmnoMMLkhsyLUYKV5GcbsEBtXnAdCyVaxibDkGig37sw33vLT3S+UCI5N6ZipSrtkLWgQdfGpMiS7NdmZisnDvxI/Yt0U30VPwod3x3tw+afYdK4+Fj7p+6+QbewmmMfNtuS2qLelR2DOdR2GazHXqJF3O9N18UGbYMe+DXtV1ElG1cQzEDBK3cNFMHFHZkyZC0vaJAc7ac46SnXzeWmwqXeoytIH/ApGGlHoPHCTEwZsBYgay8t/+nO0BxZIVKqKXnw0MXV/z9/cHzUlaloHYDcjI8LjtJv9MNxthaf5/bbMEP8Hv2/v15bi8SfP1oEAxvoJkIDWJwu4zHf+fJw8/KOiGa2zyyH011kSbN4RU33EX5o9Xg2lkdKkiMuq4/v48Glx+xmLiLCWIDumMDu8OhyGeeeG2GYYG4y6fr8V5VwT+WvWCqJbYSldbJFY3P6NuNeWE5RtBoofgiEQYOzpynXC9l8OX8NBH+svNKmijb83uxtYDvE4C4u5qIXDKc4QC54J7NMz3S6ypi8tk/A9cuyOhnImcJQx6B9Dehdx3zB7MTaI1t6bmCf1d3TLc9M7/8FT/uAPgBQOswLz1QnwUwoXlgHBLOu0K7uKi1vrIi5D4di6JSnP4ZIwsO2yNsANQkRhQR0XzC3chKqMHEUBpbL2HA6hmQvmwQRAAFIXR3CPPcNIpoAmHoW57hl/W7x5xGOYCh711xFWIVuq/Y7KxwYK8xMqMM35az+IggWxO+Sw3nSSn6+XIqL8MqTpsmFtk9xyDd9U8tK0D9FGrrSD4nxsmjNQIFbbSgw0WZoDDQyP5V/GHS18ptVQNLTRHGY4WvqqODjbagkiiUDQEWd2mUNlLL1k7sqYwbpK0HnOvrVC+oC+J3yEqYvE8MQE1kEumkCnTpJeM8KGhiEMxC2oUu31tlgbMCsnkwttpsfVx2GCwSLYYUFw9OZ61+CTTt9B6NP7R0Lx1ySoAz0NLwWI9MUoBMSjbxKp4qeaAham7tf2VBgOXuP17c1E7Z24dSPIq+MNgZuK4QFuSyJF1teUnvsoH/tR6SVKi3CzaSumuF/fly/ldj0j9h6DHgGqMNqmUerrSV0QpaYyJ7wkAxrkXUNmRQrhmKzi1TK1ePGgxSTZtBSSh8voFwGNEyiO8HTmYDMLARdlkb8koH8TDpE9svBLskiyN1Vuc5a1OpMJ8U0ZhSSIR+ENKE11u2LjdOoQWkpXThyThzb3nT/uCMHzH9XGj7OluJNoH"
        
        - name: Content-Type
          in: header
          description: Content Type
          required: true
          type: string
          default: "application/json"
          
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "IssueNonrenewal"
          
        - name: EventVersion
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "1.1.0.1"
        
        - name: Non-renewal_request
          in: body
          description: For non-renewal_request
          schema:
            $ref: '#/definitions/non-renewal_request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/non-renewal_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  non-renewal_request:
    type: object
    properties:
       EndClientUserUniqueSessionId: 
        title: "Client User Unique Session ID"
        type: string
        default: "Uniqusession"
       OwnerId:
        type: string
        default: "30"
       ServiceRequestDetail:
        type: object
        properties:
          ServiceRequestVersion:
           type: string
           default: "1.0"
          ServiceResponseVersion:
           type: string
           default: "1.0"
          OwnerId:
            type: string
            default: "24"
          ResponseType:
           title: "Response Type"
           type: string
           default: "json"
          UserName:
           title: "User Name"
           type: string
           default: "BOPAgent"
          Token:
           type: string
           default: "kMMV+5coRaP0LAqnFEIIvY+U19gRsGs6p9dSX8+actKAT7iJKK8+M9/djPLSR1R0bxlYA4OE0gGXArO3pFK8YaoUvpDersXEZA6W8Dq1ny42MhuPdxY/AA4dGl3U42kwnjphkcdmmvxsyuEoTlFrhiWph77hDEfyUtYJ4N2phiTQwrs5rtZC8qJLLY+pCth4iOfihk//O8iUOk5pjZoOEd2p6PMJ23HcA7rmUdl1IvgrxcuQymNqWNgcYjir7iOIUeDZI3tRDbgL06qL6Q76DSslbeV859MLI2RO7EQOaKw1QId4jK4B98FSW2JOoIUTP2h38fsZ2WRPvPdwfKFcwEY2g+ah5zOa9zCdXzb5YFW/ChDDTKRULT7ml2GRhYR/dCebbrdRTh2bJ8HcM5CQc1ZqPYdbiUbN0yK+V0MCLUDe+mYuxXGHoUAn6mGzxz7QQ9lP4pL1nEO+/RzjkjBg59BztctwCe+gHdYARSJMjBZPKNmpQJRwegl8dhyQWdmHsoE1LoLAT2xwrT/8Zsl0ctW2liF1ya0HtekKZpMWpZ3yuwK8xuEpVMpsdLuJy3feKQl8CxfI5ip6gIf0aiQdkEv4SYcUaN07zSpOYMEoaFYoGZjELwABpayy2xGbPWB5CEbP+ZE7KhruDn1g3aktPkZQG9/8FXlwIpRWw91wqGR7ngoBQq7jfHt4e7hBfqMNj4qVDBeEP5SaaASEnfilW9eJ6SMZlxWnS8hd8ZfZ/U915AL6fH0Bp/ThGjEm97VjVhMkgMBxUoq9+CTXEOsSg/aXVUhFp1K1nWtVeh3XFoe/U9WA3/qzescvIDQzTgK12RxUzyqWWFiguJWt7m4B9AyulAQIGPlmJVEIwsLRN3Pn6MPfFjVRvkASBjNX0xQUP5orDLSOhTkdd/J7v/AUXKuuXSlODNRoeDVogcqA1FrhS6WUJEbmgnOdmtxOr/lvtQ8riT4J+HmastPGIKUqMEf821fPmXgu9g09CGm079SuVgaKi9XcIU0p/Qnn2m/XaQcrTKuwqG0/gW1DQgabZouyQXmTCpc99QijzLV99vIwgsPNymyC5YhE34Ekb3XyFbJNSYq+vZzsUHabUF1S3/zE42g3ysy1CfGVw9PhxozL1XpCPyJjwRDToKxjJr8xeuEp1jGYlx6HeXdOykCEAS9uOH0mfCCOnj3+cMI9+6goba3Ktep/ohQxdgy2y2tRZKbAVX5rTdJTUKHSbtD6ixjZj2jETyS4m8WWgNo4uZBj46TF3IPYwIGAzJdQ2HiE4mFbsBHtiIjofJzAMRVqVGIX8Q3VD0EbSstPldj/zJNCBrc41jEbTcoCQDSY478m73AaqVBDTWgjplbd0yizYS25ypfGVfczb68juBGSNZHFhU5k9OXHoBirIaSbRFfymWHKdn2YCXjtIHx65+ye86oMA8IYDlJ+01KWwsj/ytV/Gw4ekh33AWM5mtf2qlXyxHR9qrrQTVRTY+KyVSB68zKjCF5rHmju62K4HM6FArthJckHi6Cii8ayDO5h15hk756wr+jUduPYzN5I0mhH/a0Qyx5BH9WElRsAfoPD7nHV1S37vT2C+8R8/Nv2Iwoo1D2SvLSvmfz5jcKEjm+7qKlV1aMYDEuJopP/S4PLDkmHvw2PdU1tTVVYK8dJ7SPZPa8S5OpEP8CcUs4JAN0O6INC7YMcCCur483Ni4D3f5Jcs2m6O+DzshqaiZ8E9g34SEkmK+AE3oI3SyFP999AJ7aty/Uh30xPAqL8maotvXMVvLwg6eEF1Q3DxvvBILICo4lF6hao/aUTOaXZ7lJ0grvsmPMniWHGkm0g61FL9IE275uraHBHuyfvzRsYPEqlDRzJV8N3VLmZQJ5ADfSdndS4QruGymKZ8s3Dia3gf2HTKlPaKSOEAI/+Xq0jUEBTVopd27MU79Y9obs/39pSqpaB3zeFzjndrTHtRGZFiHHFVpYBeGf1QhQc5ziE6CgBwHDb1NAC1oH16YjR3xb0oA=="
          BrowserIp:
            type: string
            default: "127.0.0.1"
          LanguageCode:
            title: "Language Code"
            type: string
            default: "en"    
          RegionCode:
            title: "Region Code"
            type: string
            default: "US"  
       Policy:
         type: object
         required:
          - EventName
          - EventVersion
          - PolicyNumber
          - NonrenewalReason
          - GroupingofNonrenewalReason
         properties:
           EventName:
            type: string
            default: "IssueNonrenewal"
           EventVersion: 
            type: string
            default: "1.1.0.1"
           ProductVerNumber:
            type: string
            default: "STARR_BASIC_2016_V1"
           ProductNumber:
            type: string
            default: "StarrBasicBOPENDR-4"
           PolicyNumber:
            type: string
            default: "1000202169"
           NonrenewalReason:
            type: string
            default: "Not Interested"
           GroupingofNonrenewalReason:
            type: string
            default: "None of the Above"
           SendEmail:
            type: string
            default: "Y"
           
  non-renewal_Success_Response:
    type: object
    required:
      - RequestStatus
      - Policy
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      Policy:
       type: object
       properties:
        EventName: 
         type: string
        EventVersion:
         type: string
        PolicyNumber:
         type: string
        NonrenewalReason:
         type: string
        GroupingofNonrenewalReason:
         type: string
        EndClientUserUniqueSessionId:
         type: string
        OwnerId:
          type: string
        ResponseStatus:
          type: string
        DocumentsInfoList:
          type: array
          items:
            properties:
              DocumentURL:
                type: string
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
        default: "FAILED"
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
        
